theme: jekyll-theme-minimal
title: "Rohith Portfolio"
logo: /assets/img/Rohith_new.jpeg

header_pages:
  - _pages/experience.md
  - _pages/resume.md
  - _pages/talks.md
  - _pages/projects.md
  - _pages/publications.md

# Configuring permalinks for all pages in the _pages directory
collections:
  pages:
    output: true
    permalink: /:title/
