theme: jekyll-theme-minimal
title: "Rohith's Portfolio"
logo: /assets/img/Rohith_new.jpeg

# header_pages:
#   - title: "Experience"
#     url: /experience/
#   - title: "Resume"
#     url: /files/Rohith_resume.pdf
#   - title: "Talks"
#     url: /talks/
#   - title: "Projects"
#     url: /projects/
#   - title: "Publications"
#     url: /publications/


# # Configuring permalinks for all pages in the _pages directory
# collections:
#   pages:
#     output: true
#     permalink: /:title/


# # Plugins
# plugins:
#   - jekyll-feed
#   - jekyll-gist
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jemoji

# # Mimic GitHub Pages with --safe
# whitelist:
#   - jekyll-feed
#   - jekyll-gist
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jemoji



# include:
#   - .htaccess
#   - _pages
#   - files
# exclude:
#   - "*.sublime-project"
#   - "*.sublime-workspace"
#   - .asset-cache
#   - .bundle
#   - .github
#   - .jekyll-assets-cache
#   - .sass-cache
#   - assets/js/_main.js
#   - assets/js/plugins
#   - assets/js/vendor
#   - CHANGELOG
#   - Capfile
#   - config
#   - Dockerfile
#   - Gemfile
#   - Gruntfile.js
#   - gulpfile.js
#   - LICENSE
#   - local
#   - log
#   - node_modules
#   - package.json*
#   - Rakefile
#   - README
#   - tmp
#   - vendor
# keep_files:
#   - .git
#   - .svn
# encoding: "utf-8"
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# # Conversion
# markdown: kramdown
# highlighter: rouge
# lsi: false
# excerpt_separator: "\n\n"
# incremental: false


# # Markdown Processing
# kramdown:
#   input: GFM
#   hard_wrap: false
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   enable_coderay: false
