theme: jekyll-theme-minimal
title: "Rohith Portfolio"
logo: /assets/img/Rohith_new.jpeg

header_pages:
  - title: "Experience"
    url: /experience/
  - title: "Resume"
    url: /files/Rohith_resumee.pdf
  - title: "Talks"
    url: /talks/
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/


# Configuring permalinks for all pages in the _pages directory
collections:
  pages:
    output: true
    permalink: /:title/
