theme: jekyll-theme-minimal
title: "Rohith Portfolio"
logo: /assets/img/Rohith_new.jpeg

header_pages:
  - index.md
  - experience.md
  - resume.md
  - talks.md
  - projects.md
  - publications.md




