theme: jekyll-theme-minimal
title: "Rohith Portfolio"
logo: /assets/img/Rohith_new.jpeg

header_pages:
  - about.md
  - experience.md
  - resume.md
  - talks.md
  - projects.md
  - publications.md


plugins:
  - jekyll-paginate
paginate: 5  # Number of posts per page
paginate_path: "/blog/page:num/"

